### ISSUE TITLE
스터디 신청 수락 / 거절 관련 로직 반영

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#102]
## 스펙
- 수락대기중인 유저의 참가신청을
  - 수락할 시: STUDY_USER 테이블의 해당 레코드의 IS_ACCEPTED 필드를 true 로 업데이트
  - 거절할 시: STUDY_USER 테이블의 해당 레코드를 삭제
- 참가신청이 수락된 유저를
  - 스터디에서 추방할 시: STUDY_USER 테이블의 해당 레코드의 IS_ACCEPTED 필드를 false 로 업데이트

## 용어
- STUDY_USER 테이블: 참가신청 정보를 저장하는 데이터베이스 테이블
- IS_ACCEPTED 필드: 참가신청 수락여부를 판단하는 필드, false 일 시 수락대기중인 상태, true 일시 수락된 상태

**Comment by rudy3091** [comment]
cc. @yesjjin99

**Comment by yesjjin99** [comment]
@rudy3091 재윤님께 여쭤봤는데, 이렇게 로직을 변경해야 할 것 같습니다!

- 참가신청이 수락된 유저를
   - 본인이 [신청 취소]를 할 시 (참가자의 경우에도 신청 취소 가능) : STUDY_USER 테이블의 해당 레코드를 삭제
   - 모집자가 [수락취소]를 통해 스터디에서 추방할 시: STUDY_USER 테이블의 해당 레코드의 IS_ACCEPTED 필드를 false 로 업데이트

**Comment by rudy3091** [comment]
관련 PR이 머지됨에 따라 close 하겠습니다

오류 발생시 reopen 및 멘션부탁드립니다 :)
