### ISSUE TITLE
비밀번호 재설정 로직 보완

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#103]
### AS-IS

- id만 알고있다면 모든 정보를 수정가능
- 별도의 인증 로직 없음

### TO-BE

- id를 기준으로 요청을 보낼 시 비밀번호만 수정 가능
- 이메일 인증 로직 있음

**Comment by rudy3091** [comment]
해당 이슈를 작업하려고 보니 비밀번호 재설정 전체 프로세스에 대한 합의가 있어야 할 것 같아 문서화작업 중에 있습니다
혹시 이 부분이 기획상으론 어떻게 되어있는지 알 수 있을까요? 제플린에 접근할 수 있는 권한이 없어 요청드립니다!

@Jeyoung-Park @yesjjin99

**Comment by fllb88** [comment]
@rudy3091 메일 써주시면, 기획문서와 제플린에 초대해드리겠습니다! 더 일찍 해드리지 못해 죄송하네요ㅜ

*제가 잘못 이해한걸수 도 있지만, 사용 플로우 상으로는 로그인 된 사용자도 비밀번호 재설정을 하려면 이메일 인증을 해야합니다!

**Comment by rudy3091** [comment]
> @rudy3091 메일 써주시면, 기획문서와 제플린에 초대해드리겠습니다! 더 일찍 해드리지 못해 죄송하네요ㅜ
> 
> *제가 잘못 이해한걸수 도 있지만, 사용 플로우 상으로는 로그인 된 사용자도 비밀번호 재설정을 하려면 이메일 인증을 해야합니다!

@fllb88 전에 인원제한으로 초대가 안됐었는데 이제 되나보네요 :)
확인하고 마무리하겠습니다! grayblack313@gmail.com 으로 초대 부탁드릴게요~

**Comment by fllb88** [comment]
@rudy3091 제플린 추가완료했습니다! 일단 적어주신 메일로 기획 문서 첨부하였습니다!

**Comment by rudy3091** [comment]
감사합니다 ;)
