### ISSUE TITLE
문의글 조회하는 api에서 유저의 중요 정보가 노출됩니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#108]
![image](https://user-images.githubusercontent.com/59302192/163216588-c4b9be7c-6458-4d04-af1c-941e48d7cd5c.png)

`GET api/study/{studyId}/comment` api에서 유저의 중요 정보가 포함되어서 내려옵니다. 수정이 필요합니다.

**Comment by Jeyoung-Park** [comment]
user 필드에 userProfile 필드가 대신 내려와도 좋을 것 같습니다.
유저 닉네임, 유저 프로필 사진 등이 필요합니다.

++) 유저가 나도 궁금해요를 클릭했는지 여부도 값으로 내려와야 합니다.

**Comment by yesjjin99** [comment]
넵 수정하겠습니다!
