### ISSUE TITLE
운영에서 CORS 에러 발생

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#114]
caustudy.com 도메인에서 접근했을 때 CORS 에러가 발생합니다. 이에 대한 대응이 필요합니다.

![image](https://user-images.githubusercontent.com/59302192/164257332-e896f92c-0f68-4d85-ab8d-356948c1a1d8.png)

**Comment by rudy3091** [comment]
#115

**Comment by rudy3091** [comment]
close 하겠습니다!
