### ISSUE TITLE
참가신청 수락 api의 반환값에 capacity, members_count 포함해야 함

### ISSUE THREAD

**Issue by yesjjin99** [caulipse/caulipse-server#118]
`/api/study/user/{studyid}/accept` 엔드포인트에서 스터디 정원과 현재 멤버수를 함께 return 해야 합니다.

**Comment by rudy3091** [comment]
참가신청 수락을 하기 전에 이전 api 호출로 이미 알고있는 인원수 정보를 해당 api 요청의 응답결과를 기준으로 업데이트하는것으로 논의되었습니다

ex)
- `PATCH /api/study/user/:studyid/accept` 의 응답코드가 200 -> 기존 capacity 값에 +1
- 응답코드가 403 -> 기존 capacity 값 업데이트하지 않음

이에 본 이슈는 close 하겠습니다 :)
