### ISSUE TITLE
북마크 조회하는 api에 dueDate가 포함되어서 오지 않습니다. (+신청 스터디)

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#124]
북마크 조회하는 api에 dueDate가 포함되어서 오지 않습니다. 
기존에 포함되어서 왔는데 이번에 수정사항이 반영되면서 빠진 것 같습니다.
`GET /api/user/bookmark`
`GET /api/user/study/applied` 의 리스폰스에도 dueDate가 추가되어야 합니다.
![image](https://user-images.githubusercontent.com/59302192/166134731-84e263a3-07fa-490c-a181-3a5fd4079c08.png)

**Comment by Jeyoung-Park** [comment]
@yesjjin99 이거 진행상황은 어떻게 되고 있나요??
확인해보니 북마크 리스폰스에서도 dueDate가 내려오지 않고 있습니다.

**Comment by yesjjin99** [comment]
@Jeyoung-Park 반영해서 올려놓겠습니다! 죄송합니다🙏
