### ISSUE TITLE
참가중인 사용자 목록 조회 api 작동 안 함

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#128]
해당 스터디에 참여중인(참가신청이 수락된) 사용자 목록을 조회하기 위한 엔드포인트가 동작하지 않습니다.
스터디 정보에서 인원이 차 있다고 나오는데 리턴 값은 빈 배열로 찍힙니다.

api 정보: `GET /api/study/user/{studyId}/participants'`

**Comment by Jeyoung-Park** [comment]
댓글 조회도 마찬가지로 작동하지 않습니다.

**Comment by rudy3091** [comment]
말씀해주신 문제는 컨트롤러 로직의 문제가 아니라 목데이터의 특성상 생기는 문제로 파악됩니다
목데이터를 작업할때 정상적으로 동작하는지는 직접 데이터를 넣어주며 테스트할 예정이라 하셔서 이렇게 작업했었던 것 같네요..

```typescript
  study.capacity = rand(5, 11);
  study.membersCount = rand(1, 11);

  // ...

  const studyUser = new StudyUser();
  studyUser.user = user;
  studyUser.study = study;
  studyUser.isAccepted = false;
  studyUser.tempBio = `hello i'm User#${user.id}, applying study ${study.title}`;
```

인원이 차 있다고 나오는건 위 코드처럼 capacity 와 membersCount 에 난수를 넣었기 때문이고, studyUser 레코드를 만들어줄때 isAccepted 필드에 false 값만 할당해줘서 참가중인 사용자가 없다는 의미로 빈 배열이 내려오고 있습니다

댓글 조회의 경우는 제가 작업한 부분이 아니라 nested 처리방법을 몰라 철저하게 모델링하지 못했는데 목데이터의 말씀주신 두 부분 모두 수정이 필요하실까요??

**Comment by Jeyoung-Park** [comment]
@rudy3091 댓글 조회는 현재 정상적으로 작동합니다.
`GET /api/study/user/{studyId}/participants` api 호출했을 떄 404 에러가 발생하는데 이것도 목데이터 이슈인지 확인해주시면 감사드리겠습니다 🙇

**Comment by Jeyoung-Park** [comment]
> @rudy3091 댓글 조회는 현재 정상적으로 작동합니다. `GET /api/study/user/{studyId}/participants` api 호출했을 떄 404 에러가 발생하는데 이것도 목데이터 이슈인지 확인해주시면 감사드리겠습니다 🙇

@yesjjin99 @rudy3091 이 이슈 확인해주시면 감사드리겠습니다 🙏

**Comment by rudy3091** [comment]
> > @rudy3091 댓글 조회는 현재 정상적으로 작동합니다. `GET /api/study/user/{studyId}/participants` api 호출했을 떄 404 에러가 발생하는데 이것도 목데이터 이슈인지 확인해주시면 감사드리겠습니다 🙇
> 
> @yesjjin99 @rudy3091 이 이슈 확인해주시면 감사드리겠습니다 🙏

@Jeyoung-Park 스터디 신청 관련 api 는 `/api/study/:studyid/user/*` 으로 요청 보내주셔야 합니다

<img width="805" alt="image" src="https://user-images.githubusercontent.com/61422890/169862285-c8aebe48-a34c-4003-a5fb-177f3b17f978.png">

**Comment by Jeyoung-Park** [comment]
@rudy3091 넵 정상 작동하는 거 확인했습니다. close하겠습니다 🙏
