### ISSUE TITLE
스터디 생성 api 버그

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#129]
request 정보는 이미지 캡쳐로 대체하겠습니다.

![image](https://user-images.githubusercontent.com/59302192/167269043-cda509a6-d1c2-49a8-98ed-6c534bb7de17.png)
![image](https://user-images.githubusercontent.com/59302192/167269071-ac43b6b1-8bfe-4263-be0f-305887c33b41.png)
![image](https://user-images.githubusercontent.com/59302192/167269081-f55ce41f-9421-4a9f-8235-12c303a741a5.png)

**Comment by yesjjin99** [comment]
@Jeyoung-Park 현재 스터디 엔티티에서 weekday와 location이 array 타입으로 되어있어서 스터디 생성, 스터디 업데이트 api 요청 보내주실 때 배열값으로 넘겨주셔야 잘 동작합니다! 스웨거 문서도 함께 변경해놓았으니 확인 후 다시 시도해주시고 또 안되시는 부분 있으면 말씀해주세요

**Comment by Jeyoung-Park** [comment]
> @Jeyoung-Park 현재 스터디 엔티티에서 weekday와 location이 array 타입으로 되어있어서 스터디 생성, 스터디 업데이트 api 요청 보내주실 때 배열값으로 넘겨주셔야 잘 동작합니다! 스웨거 문서도 함께 변경해놓았으니 확인 후 다시 시도해주시고 또 안되시는 부분 있으면 말씀해주세요

넵 확인 감사합니다! 수정해보고 말씀드리겠습니다 👍

**Comment by Jeyoung-Park** [comment]
@yesjjin99 클라 쪽에서 request 타입 변경해서 해주니까 잘 동작하네요! 감사합니다
https://github.com/caulipse/caulipse-ui/pull/358
