### ISSUE TITLE
북마크, 신청중, 모집중 카운트 받을 수 있는 api가 있나요?

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#131]
마이페이지에서 북마크, 신청중, 모집중 카운트를 받아야하는데 이거 받을 수 있는 api가 있나요?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/59302192/167288783-0cf83287-9cdd-4d27-af74-ef47791d1b89.png">

**Comment by rudy3091** [comment]
북마크: GET /api/user/bookmark
신청중: GET /api/user/study/applied
모집중: GET /api/study/my-study

의 엔드포인트에서 데이터를 받을 수 있는것으로 보입니다
마이페이지 접근시 해당 api들 호출해주고 length 프로퍼티 접근해서 가져올 수 있을 것 같습니다 :)

**Comment by Jeyoung-Park** [comment]
이거는 클라에서 처리하도록 하겠습니다.
