### ISSUE TITLE
스터디 상세 patch시 USER_ID 필드 관련 에러 발생

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#132]
![image](https://user-images.githubusercontent.com/59302192/167298334-8bfd7333-f87e-43a0-88e9-bd7a87cffa67.png)
![image](https://user-images.githubusercontent.com/59302192/167298343-21f7d3fe-4613-46f4-b62e-b5ede84c4109.png)
![image](https://user-images.githubusercontent.com/59302192/167298350-dd54a829-7567-4894-8d17-af8b435bf7d3.png)

**Comment by yesjjin99** [comment]
@Jeyoung-Park 해당 이슈는 현재 잘 동작하나요??

**Comment by Jeyoung-Park** [comment]
@yesjjin99 넵 문제 없는 것 같아 close하겠습니다 🙏
