### ISSUE TITLE
스터디 마감하기 API 가 정상 동작하지 않음 

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-server#135]
스터디 마감하기 API (patch /api/study/${study_id}/close) 호출 시 400 에러가 발생합니다. 

<img width="1243" alt="스크린샷 2022-05-12 오후 11 56 46" src="https://user-images.githubusercontent.com/56914200/168105317-69f2a97c-812d-487f-b403-c126909701cf.png">

<img width="808" alt="스크린샷 2022-05-12 오후 11 56 52" src="https://user-images.githubusercontent.com/56914200/168105323-a9f24508-1713-483e-8ce0-726f58c159de.png">

**Comment by Jeyoung-Park** [comment]
@yesjjin99 저는 스터디 마감하기 클릭 시 이런 오류가 발생했습니다!

![image](https://user-images.githubusercontent.com/59302192/169663129-40277290-c879-4e8b-b997-b6cca564ecbc.png)
![image](https://user-images.githubusercontent.com/59302192/169663142-4adde086-9390-442f-adfe-5bf77fd81c8d.png)

**Comment by yesjjin99** [comment]
@Jeyoung-Park @taechonkim 확인했습니다! 내 스터디 조회, 검색, 마감하기 모두  해결하겠습니다 🙏
