### ISSUE TITLE
회원가입 API 가 동작하지 않음 

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-server#140]
회원가입 시 400 에러가 발생합니다. 아래 에러 메시지 참고 부탁드립니다. 

message: "회원가입 실패: (0 , crypto_1.randomUUID) is not a function"

**Comment by Jeyoung-Park** [comment]
@rudy3091 이 이슈는 해결된 상태인가요?

**Comment by rudy3091** [comment]
@Jeyoung-Park 현재까진 재현이 안되는것 같습니다. close 해도 되지 않을까요?

**Comment by Jeyoung-Park** [comment]
@rudy3091 아 그렇군요! 그렇다면 닫아주셔도 됩니다. 배포 서버에 반영돠어있으면 저도 한 번 확인해볼게요
