### ISSUE TITLE
스터디 신청 취소 api가 정상 동작하지 않습니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#142]
![image](https://user-images.githubusercontent.com/59302192/169681174-adc7f83d-f73d-48d9-b4e2-8f6570380269.png)

**Comment by rudy3091** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/61422890/169681756-9829ed29-8739-4eda-83b2-1a70a4ffea29.png">

스터디 참가신청 취소는 위 엔드포인트로 요청해주셔야 합니다

시도해보시고 이상 없으시면 close 부탁드릴게요 :)

**Comment by Jeyoung-Park** [comment]
넵 바뀐 엔드포인트로 적용했는데 잘 작동하였습니다. 감사합니다 🙇
