### ISSUE TITLE
메일인증없이 로그인이 되는 이슈

### ISSUE THREAD

**Issue by fllb88** [caulipse/caulipse-server#147]
메일 발송(=회원가입 1단계)만 하면, 인증없이도 회원가입에 성공합니다.

이렇게 생성된 계정은, 유저 프로필 정보 없이 계정이 유지되지만, [스터디 등록] [스터디 신청] 등과 같이 유저 프로필 정보가 필요한 요청에 대해서는 응답이 실패합니다

<img width="1425" alt="스크린샷 2022-05-24 오후 11 16 45" src="https://user-images.githubusercontent.com/103623866/170057568-c9c32cfb-7370-454a-9e80-ea5d7506df13.png">
.

**Comment by rudy3091** [comment]
#140 에서와 같이 회원가입 과정에서 에러가 발생하는것으로 보입니다
#141 이슈 대응이 먼저라 완료되는대로 대응하겠습니다

**Comment by rudy3091** [comment]
#148 과 중복 내용으로 판단되어 close 하겠습니다
