### ISSUE TITLE
인증메일 발송 이슈

### ISSUE THREAD

**Issue by fllb88** [caulipse/caulipse-server#148]
현재 회원가입 1단계를 통해 '메일발송' 이 되었다는 스낵바를 확인하였음에도, 중앙대 이메일(포탈)에서 해당 메일이 오지 않습니다.

*이 상태에서 로그인을 하면, 유저정보없는 계정으로 로그인됩니다

**Comment by Jeyoung-Park** [comment]
![image](https://user-images.githubusercontent.com/59302192/170080150-a98b1a33-2d6a-407b-ad63-b64aa043225e.png)

![image](https://user-images.githubusercontent.com/59302192/170080050-8a2dff4e-2120-4c4d-995f-4c285a815836.png)

게정을 생성되는데 메일이 오지 않습니다. 400 bad request로 뜨는데 엔드포인트 주소가 바뀌었나요??

**Comment by Jeyoung-Park** [comment]
메일 caulipse814@gmail.com로 바꿔야 합니다. @rudy3091

**Comment by rudy3091** [comment]
서버의 `.env` 파일에 메일 관련 설정이 누락되어 생기는 문제로 파악됐습니다... -_-
인증 없이 로그인되는 문제는 로그인 시 `GUEST` 계정인지 파악하는 로직이 없어 생기는 문제로 생각됩니다
