### ISSUE TITLE
참가 신청 취소에서 400 에러가 반환됩니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#163]
![image](https://user-images.githubusercontent.com/59302192/172036973-7d0208ae-11f4-463c-ace7-2865f21e7bcf.png)
![image](https://user-images.githubusercontent.com/59302192/172036976-b473fe13-1a7c-487f-87e6-662eecaba5fc.png)

스웨거에 나와 있는 대로 요청을 보냈는데 400 에러가 반환됩니다. 확인해주시면 감사드리겠습니다!!

**Comment by rudy3091** [comment]
요청 보내주신 주소는 참가신청 수정 api 같습니다!
혹시 `DELETE /api/study/{studyid}/user/{userid}`  api가 정상동작하는지 확인 부탁드려도 될까요?

**Comment by Jeyoung-Park** [comment]
> 요청 보내주신 주소는 참가신청 수정 api 같습니다! 혹시 `DELETE /api/study/{studyid}/user/{userid}` api가 정상동작하는지 확인 부탁드려도 될까요?

아 제가 api를 잘못 적용했나 보군요 ㅠㅜㅠ
모집자가 수락한 유저를 수락 취소하는 상황인데 표시해주신 api를 사용하면 되는 건가요??

![image](https://user-images.githubusercontent.com/59302192/172037611-12d6b87a-570f-4376-a940-b44fbe84383b.png)

**Comment by rudy3091** [comment]
넵 쿠키에 들어있는 유저 정보를 이용해서 사용자가 직접 탈퇴하는건지, 호스트가 강퇴하는건지 결정하는 로직입니다!

**Comment by Jeyoung-Park** [comment]
> 넵 쿠키에 들어있는 유저 정보를 이용해서 사용자가 직접 탈퇴하는건지, 호스트가 강퇴하는건지 결정하는 로직입니다!

집 인터넷 이슈가 있어서 답장이 늦었습니다 ㅠㅠ

이 경우에는 500 에러가 반환됩니다.

![image](https://user-images.githubusercontent.com/59302192/172038778-a6021a3e-997b-43ca-a522-269e36738196.png)
![image](https://user-images.githubusercontent.com/59302192/172038783-7d8866e5-4838-4784-a3d2-2d07d8435973.png)
