### ISSUE TITLE
알림텍스트 버그

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#189]
*알림: ~~님이 신청 요청을 보냈어요 에서 undefined 로 표시됨

*아직 알림의 모든 케이스들에 대해 테스트를 진행하지 못한 상태입니다. 다음 배포 적용된 이후, 알림 케이스들 일괄적으로 확인후 다시 정리해 드리겠습니다. 

https://github.com/caulipse/caulipse-ui/issues/492

cc. @fllb88

**Comment by fllb88** [comment]
@yesjjin99 
![E38C6765-70B9-4C7D-A676-70EB18C22540](https://user-images.githubusercontent.com/103623866/175754942-3b1b6937-002e-44b1-a6f7-7709a45a9466.jpeg)

디코에 말씀드린 사항입니다. 혹시 몰라 깃허브 이슈에 자료추가해드릴게요!
