### ISSUE TITLE
스터디 단 건 조회하는 api에서 유저의 신청 여부 정보가 필요합니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#65]
- 신청하기 버튼 활성화 여부를 표시하기 위해 스터디 단건 호출하는 api에서 api 호출하는 유저의 신청 여부 데이터가 필요합니다.
![image](https://user-images.githubusercontent.com/59302192/159271961-d623dafd-4a48-4bbc-872b-1ed2740b1b23.png)

**Comment by Jeyoung-Park** [comment]
- 댓글 조회하는 로직에 유저 네임, 유저 이미지, 나도 궁금해요, 유저가 나도 궁금해요 클릭했는지 여부 등 추가적인 필드가 필요합니다
- #86 과도 관련이 있습니다
- 엔드포인트: `api/study/{studyId}/comment`

**Comment by Jeyoung-Park** [comment]
@rudy3091 @yesjjin99 이 이슈는 진행상황이 어떻게 되나요??

**Comment by rudy3091** [comment]
저는 아직 맡아서 작업중이지 않았습니다..!
제 생각에는 유저의 신청 여부는 해당 스터디의 참가신청이 수락된 인원을 조회하는 api를 조회하고 그 배열을 순회하며 사용자가 배열 내에 존재하는지 확인하는 정도만 해도 충분할 것 같습니다 :)

**Comment by rudy3091** [comment]
나도 궁금해요, 나도 궁금해요 클릭 여부는 우선순위 낮음, 북마크했는지 여부는 우선적으로 수용
