### ISSUE TITLE
스터디 정보를 수정할 때 개선사항

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#67]
AS-IS: 스터디 정보를 수정하기 위해 요청 바디에 모든 필드를 전달해야됨
TO-BE: 스터디 정보를 수정할 필드만 전달하면 됨

+) 조회수, 북마크수 등의 필드는 수정되면 안되기 때문에 해당 필드들을 걸러서 400 코드를 응답시키도록 하는 로직 필요

**Comment by rudy3091** [comment]
스터디 엔티티 필드:
- id
- 생성일자
- 제목
- 본문
- 진행요일
- 진행빈도
- 진행장소
- 개설 유저 id
- 최대 참가인원수
- 참가인원 수
- 빈자리 수
- 모집중 여부
- 카테고리 code
- 조회수
- 북마크 수

스터디 정보 갱신 요청을 통해 변경가능해야 하는 필드:
- 제목
- 본문
- 진행요일
- 진행빈도
- 진행장소
- 최대 참가인원수
- 모집중 여부
- 카테고리 code

**Comment by rudy3091** [comment]
@yesjjin99 @Jeyoung-Park 피드백 부탁드립니다!

**Comment by Jeyoung-Park** [comment]
@rudy3091 저는 좋은 것 같습니다!

**Comment by rudy3091** [comment]
@taechonkim 멤버로 추가가 안되어있어 노티가 갈 지 모르겠습니다
작업 완료돼서 이슈 닫아두겠습니다! 오류 생기거나 추가 요청사항 있으면 다시 열어주세요 :)
