### ISSUE TITLE
수락 대기중인 유저들의 리스트를 가져오는 api가 필요합니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#68]
- 수락 대기 중인 유저들의 리스트를 가져오는 api가 필요합니다.
- 추가적으로 참여인원은 인증 미들웨어 없이 비로그인인 상태에서도 호출이 가능하도록 수정되어야 합니다. 
![image](https://user-images.githubusercontent.com/59302192/159727106-e3bec2c5-1be6-4601-bdd9-82848ab343a0.png)

**Comment by rudy3091** [comment]
해당부분은 제 이번주 작업범위 안인데요, 기획문서를 봐도 잘 이해가 되지 않아 오늘(목요일) 회의에서 한번 짚고나서 작업하고 싶은데 그렇게 해도 될까요?

**Comment by Jeyoung-Park** [comment]
> 해당부분은 제 이번주 작업범위 안인데요, 기획문서를 봐도 잘 이해가 되지 않아 오늘(목요일) 회의에서 한번 짚고나서 작업하고 싶은데 그렇게 해도 될까요?

아 이 메시지를 이제 봤네요! 중간중간에 편하게 연락 주세요!

**Comment by rudy3091** [comment]
해당 이슈도 확인되면 close 부탁드리겠습니다 🙏 #81
