### ISSUE TITLE
신청 스터디에 추가적인 필드가 필요합니다

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#72]
![image](https://user-images.githubusercontent.com/59302192/159946629-3958e9c0-c20b-4bd1-9152-f5e0454c53a7.png)

신청 스터디디에서 유저의 수락 여부, 스터디의 현재 참가 인원, 스터디의 최대 참가 인원 데이터가 추가적으로 필요합니다 🙏 
@rudy3091

**Comment by rudy3091** [comment]
확인했습니다!

**Comment by rudy3091** [comment]
오류 발생시 re-open 부탁드리겠습니다 :)
