### ISSUE TITLE
get /api/notice 에서 offset, limit이 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#73]
- 공지사항 목록 조회하는 api에서 offset과 limit이 작동하지 않는 것 같습니다.

**Comment by rudy3091** [comment]
요청 url과 쿼리스트링, 결과가 어떻게 되나요??

**Comment by Jeyoung-Park** [comment]
> 요청 url과 쿼리스트링, 결과가 어떻게 되나요??

앗 늦게 확인했네요 ㅠ
`http://localhost:4000/api/notice?offset=1&limit=1` 제 로컬에서 이렇게 요청했을 떄 리스폰스가 아래와 같이 왔습니다.

![image](https://user-images.githubusercontent.com/59302192/160275442-632d5307-a5dc-48c2-bbbc-e61c0c10e63d.png)

**Comment by rudy3091** [comment]
정상동작 확인되면 close 부탁드리겠습니다 (- -) (_ _)

**Comment by Jeyoung-Park** [comment]
정상동작하는 것 같습니다. 감사합니다 🙇

**Comment by Jeyoung-Park** [comment]
@rudy3091 정상작동하지 않는 부분이 있는 것 같아서 다시 오픈했습니다 ㅠㅠ
db에 notice 데이터가 10개 있는 걸로 알고 있는데 아래와 같은 현상이 발견되었습니다.
offset에 0, limit에 8을 넣고 조회했을 때 -> 8개 조회
offset에 1, limit에 8을 넣고 조회했을 떄 -> 8개 조회 (정상적으로 작동했다면 2개 조회되어야 함)
offset에 2, limit에 8을 넣고 조회했을 때 -> 8개 조회 (정상적으로 작동했다면 0개 조회되어야 함)

**Comment by rudy3091** [comment]
@Jeyoung-Park  확인해보시고 close 부탁드리겠습니다 :)

**Comment by Jeyoung-Park** [comment]
잘 작동하는 것 같습니다. 감사합니다 🙏
