### ISSUE TITLE
닉네임 유효성 체크 

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#74]
닉네임 유효성을 어떻게 정해야할지 프론트 -백 사이에 기준을 정해야합니다.
재윤님께서는 한글 4~8자 정도가 괜찮다고 하시는데, db에 맞는 적절한 기준을 합의하면 좋을 것 같습니다.
@yesjjin99

**Comment by yesjjin99** [comment]
확인해 보니까 4~8자로 정해도 될 것 같습니다!

**Comment by Jeyoung-Park** [comment]
@yesjjin99 한글 영어 숫자 기준은 상관없나요?

**Comment by yesjjin99** [comment]
한글, 영문, 숫자 255자까지 저장 가능한 상태입니다. 영문 이외의 기준으로는 오차가 있을 수 있지만 mysql에서는 크게 차이가 안 나는 것 같아요.

**Comment by fllb88** [comment]
@Jeyoung-Park @yesjjin99 그러면 최종적으로 "영어,한글,숫자 혼합으로 최소 4자~최대 8자로 정해지는걸까요??

**Comment by Jeyoung-Park** [comment]
> @Jeyoung-Park @yesjjin99 그러면 최종적으로 "영어,한글,숫자 혼합으로 최소 4자~최대 8자로 정해지는걸까요??

@mnmchoco 아 이거 제가 기준 찾고 있는데 조만간 정의해서 말씀드릴게요!

**Comment by Jeyoung-Park** [comment]
@fllb88 @yesjjin99 영어, 한글, 특수문자(- _ .), 숫자 포함해서 2~12자로 하려고 합니다. 4~8자는 영어를 사용하는 경우에 글자수가 부족할 수도 있을 것 같아서요! 
변경하시고 싶으신 부분 있으시면 요청해 주세요!

**Comment by Jeyoung-Park** [comment]
https://github.com/caulipse/caulipse-ui/pull/276
프론트 회원가입 pr에서 닉네임 유효성 추가해서 작업했습니다.

**Comment by fllb88** [comment]
글자수 넣어봤는데요, 가장 가로값 많이 차지하는 한글로만 채웠을때, 10자가 가장 별 문제 없을듯합니다. 

![image](https://user-images.githubusercontent.com/103623866/163707803-5112dc4c-c041-4e32-8173-e5a799409c01.png)
< 12글자

<img width="832" alt="스크린샷 2022-04-17 오후 5 49 43" src="https://user-images.githubusercontent.com/103623866/163707514-8349ca04-e494-480b-8921-71962c52b04a.png">

*최대글자는 10자로 하고, 최소는 2자
*영어 / 한글 / 숫자 사용 **_( + 특수문자? )_**
*띄어쓰기는 [ _ ] 로 표시

가 최종적인 유효성일거 같네요! 

+ 아 그런데, 특수문자도 닉네임에 사용하는 건가요?

**Comment by Jeyoung-Park** [comment]
> 글자수 넣어봤는데요, 가장 가로값 많이 차지하는 한글로만 채웠을때, 10자가 가장 별 문제 없을듯합니다.
> 
> ![image](https://user-images.githubusercontent.com/103623866/163707803-5112dc4c-c041-4e32-8173-e5a799409c01.png) < 12글자
> 
> <img alt="스크린샷 2022-04-17 오후 5 49 43" width="832" src="https://user-images.githubusercontent.com/103623866/163707514-8349ca04-e494-480b-8921-71962c52b04a.png">
> 
> *최대글자는 10자로 하고, 최소는 2자 *영어 / 한글 / 숫자 사용 **_( + 특수문자? )_** *띄어쓰기는 [ _ ] 로 표시
> 
> 가 최종적인 유효성일거 같네요!
> 
> * 아 그런데, 특수문자도 닉네임에 사용하는 건가요?

아 확인이 늦었네요
특수문자는 - _ . 이거 세 개만 포함하려고 합니다.

**Comment by Jeyoung-Park** [comment]
[이 pr](https://github.com/caulipse/caulipse-ui/pull/373)에서 닉네임 최대 길이 10자로 수정하였습니다. 이 이슈는 클로즈하겠습니다
