### ISSUE TITLE
스터디 목록 조회 시 필터/정렬 보완

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#76]
### AS-IS

- 필터링 항목을 여러개 받을 수 없음
- 카테고리 코드 기준 필터링에 상위 카테고리를 지정할 수 없음 (스터디 엔티티에 저장되는 카테고리 코드는 하위 카테고리 코드)
  - https://github.com/caulipse/caulipse-ui/issues/106
- 기본 정렬 옵션이 존재하지 않음

### TO-BE & Possible actions

- 필터링 항목을 여러 개 받을 수 있음 (ex: .../api/study?weekday=~~월,목~~mon,thu) <- #91 이후 확인
  - , 를 기준으로 split 또는 파싱 로직 추가
- 상위 카테고리를 기준으로 필터링하면 하위 카테고리코드에 해당하는 스터디들이 모두 반환됨
  - `categoryCode % 100` 을 기준으로 쿼리 등
- 기본적으로 생성일자 기준으로 내림차순 정렬하여 반환
  - service/study/index.ts 수정

**Comment by yesjjin99** [comment]
제가 했던 부분이어서 확인 후 작업하겠습니다! 👍
