### ISSUE TITLE
마감기능 과 스터디 목록 조회 기능 연동

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#77]
- 아래 페이지에서의 `마감항목 숨기기` 기능 지원을 위함
- 스터디목록 조회시 마감여부를 체크
- 기본값은 OFF (마감항목 포함)

<img src="https://user-images.githubusercontent.com/61422890/160273792-5dbb87a3-969c-4598-9a4e-cbf24c5934b8.png" width="300" />

**Comment by yesjjin99** [comment]
넵, 감사합니다! 확인했습니다 :)
