### ISSUE TITLE
로그인 시 유저 정보 암호화

### ISSUE THREAD

**Issue by rudy3091** [caulipse/caulipse-server#78]
프론트엔드와 인터페이스 통일하여 로그인 시 보여질 정보가 암호화되어 표시되도록 수정

**Comment by rudy3091** [comment]
@taechonkim 안녕하세요 미리님
이전에 sha256을 이용한 암호화를 제안해 주셨는데, 시도해본 결과 sha256은 복호화가 불가능한 알고리즘으로 보입니다..! 혹시 생각하신 프로세스가 아래 중 어떤것인지 여쭙고 싶습니다!

- 브라우저에서 sha256 알고리즘으로 암호화, 서버에서 복호화하여 다시 서버의 암호화 파라미터로 암호화하여 데이터베이스에 저장
- 브라우저에서 sha256 알고리즘으로 암호화, 서버에서 복호화 없이 서버의 암호화 파라미터로 암호화하여 데이터베이스에 저장
- 브라우저에서 sha256 알고리즘으로 암호화, 서버에서 별도의 암호화 없이 바로 데이터베이스에 저장

여유있으실 때 답변 부탁드리겠습니다 🙇

**Comment by taechonkim** [comment]
@rudy3091  안녕하세요 현민님~ 저는 2번안을 생각하고 제안드렸었습니다! 혹시 이슈가 있을까요?

**Comment by rudy3091** [comment]
@taechonkim 아뇨 감사합니다! 정확히 인식을 맞추고 개발해야 할 것 같아서 문의드렸습니다 :) 다음주 중으로 완료하고 멘션드리겠습니다!

**Comment by taechonkim** [comment]
@rudy3091 넵 감사합니다! 프론트도 개발후 멘션드리겠습니다 :D
