### ISSUE TITLE
스터디 수정 api request body에 USER_ID가 필수적으로 들어가게 되어 있습니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#83]
스터디 수정하는 api 호출할 때 USER_ID를 필수적으로 request body 객체 안에 넣어줘야 하는 건가요?
토큰에서 req.user 정보를 받아와서 사용하면 더 깔끔할 거 같은데 이 부분에 대한 합의가 필요할 것 같습니다!

![image](https://user-images.githubusercontent.com/59302192/161094264-4bf31963-d501-420b-b163-41bed3f3e304.png)

**Comment by rudy3091** [comment]
요청 엔드포인트와 body도 알려주실 수 있을까요?
현재 보이는 에러메시지로는 요청이 잘못되어서라기보단 서버 코드에 문제가 있어보입니다
또 #67 에서 해당부분 수정할 예정이라 같이 저기에 추가해주시면 좋을 것 같아요 :)

**Comment by Jeyoung-Park** [comment]
> 요청 엔드포인트와 body도 알려주실 수 있을까요? 현재 보이는 에러메시지로는 요청이 잘못되어서라기보단 서버 코드에 문제가 있어보입니다 또 #67 에서 해당부분 수정할 예정이라 같이 저기에 추가해주시면 좋을 것 같아요 :)

요청 엔드포인트: patch `api/study/{studyId}`
![image](https://user-images.githubusercontent.com/59302192/161392178-c051f884-a418-4ec0-affd-5ddc1269ce16.png)

userId는 수정이 되면 안 되는 부분인데 코드 상으로 이 부분을 요구하는 것 같아요! #67 에는 추가되지 않아도 될 항목일 것 같습니다

**Comment by rudy3091** [comment]
#90 머지 이후 다시 확인 부탁드립니다 🙏

**Comment by Jeyoung-Park** [comment]
확인되어서 클로즈하겠습니다 감사합니다 :)
