### ISSUE TITLE
enum값이 바뀜에 따라 서버에서 crash 발생

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-server#96]
- #71 에서 enum 값들이 바뀌면서 목 데이터들과 맞지 않아 버그가 발생하는 것 같습니다. (기존 목데이터와의 충돌인 것 같습니다. 목 데이터 모두 삭제했을 떄는 에러가 발생하지 않습니다.)
- 새로운 목 데이터 스크립트를 생성하는 게 좋을까요..? 

![image](https://user-images.githubusercontent.com/59302192/161787703-987697eb-4e65-4272-ad65-8b38029a549a.png)

**Comment by rudy3091** [comment]
빠르게 작업해보겠습니다..!

**Comment by Jeyoung-Park** [comment]
> 빠르게 작업해보겠습니다..!

넵 감사합니다..!! 혹시 현민님도 같은 이슈 발생하시는지도 봐주시면 감사드리겠습니다 🙇

**Comment by rudy3091** [comment]
> 넵 감사합니다..!! 혹시 현민님도 같은 이슈 발생하시는지도 봐주시면 감사드리겠습니다 🙇

아직 체크는 안해봤는데 아마 똑같이 에러생길것 같아요ㅋㅋㅋ 빠르게 목데이터 만들어보겠습니다

**Comment by Jeyoung-Park** [comment]
해당 사항 적용되어서 close하겠습니다.
